### ISSUE TITLE
No value given for one or more required parameters

### ISSUE THREAD

**Issue by michzimny** [michzimny/aktywator#41]
Co to może być? Wyskakuje po otwarciu bws.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Data.OleDb.OleDbException: No value given for one or more required parameters.
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextErrorHandling(OleDbHResult hr)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextForSingleResult(tagDBPARAMS dbParams, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommand(CommandBehavior behavior, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteScalar()
   at Aktywator.Sql.selectOne(String q, Boolean checkForRow)
   at Aktywator.Bws.convertSettingsPerSection()
   at Aktywator.Bws.convert()
   at Aktywator.MainForm.MainForm_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

```

**Comment by michzimny** [comment]
Hm... to mógł być brak systemowych praw zapisu do bws-a.

**Comment by emkael** [comment]
Jeżeli to się zmieniło między wywołaniami i drugie wywołanie zadziałało, to bardzo możliwe - teraz na starcie wykonywane są praktycznie zawsze te same operacje (tj. raczej nie jest tak, że pierwsze odpalenie BWSa naprawiło coś w pliku).

**Comment by michzimny** [comment]
Cannot reproduce.

Więc pewnie jak wyżej.
